name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31.7.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run the package
        run: nix run . -- -l 100